# -*- coding: utf-8 -*-
"""
Cohort definition: who is in the study, and which controls they are matched to.

This is pipeline logic, not exploration — it produces the freq_match_*.csv
files that every downstream analysis depends on. It lives here rather than in
a notebook so that it runs top to bottom in one process, can be tested, and
can be regenerated by `scripts/build_cohort.py` with a recorded commit hash.

Inclusion criteria, applied in this order:

  1. age >= 20
  2. a valid accelerometer recording covering the full 9 days
     (PAXSTS == 1 and PAXLDAY == '9')
  3. complete data on every matching variable

Controls are frequency matched to cases on age band, sex, race/ethnicity,
season of wear and income-to-poverty band, sampling up to `control_ratio`
controls per case within each stratum.

Nothing here prints or plots; callers decide how to report. The functions were
promoted out of notebook 03 with the sampling algorithm unchanged, so the
cohorts they produce are identical to the ones already in use.
"""

import numpy as np
import pandas as pd

from . import cohort as ch
from . import nhanes as nhn
from . import paths

# The variables controls are matched on
MATCH_COLS = [
    "age_bin",
    "sex_label",
    "race_label",
    "season",
    "PIR_cat",
]

MIN_AGE = 20
DEFAULT_CONTROL_RATIO = 4
DEFAULT_SEED = 42


def bin_age(ages):
    """
    Band ages for matching: under 20, then five-year bands to 80+.

    The under-20 band exists only so the bins cover the whole range; those
    participants are excluded by the age criterion before matching.
    """
    # ASCII hyphens rather than en dashes: these labels are printed into job
    # logs, and a Windows console renders en dashes as mojibake. The labels are
    # names for the bins only and are never persisted, so this does not affect
    # which participants are selected.
    bins = [0, 20] + list(range(25, 81, 5)) + [np.inf]
    labels = ["0-19", "20-24", "25-29", "30-34", "35-39",
              "40-44", "45-49", "50-54", "55-59", "60-64",
              "65-69", "70-74", "75-79", "80+"]

    return pd.cut(ages, bins=bins, labels=labels, right=False)


def eligible_participants(year, base_path=None):
    """
    Apply the inclusion criteria and label the demographics.

    Returns
    -------
    df_all : DataFrame
        Every adult with a valid recording — the pool controls are drawn from.
    df_pwe : DataFrame
        Those of them identified as having epilepsy.
    """
    demo = nhn.load_partial_demo(year, base_path)
    adults = demo[demo["age"] >= MIN_AGE]

    pwe_index = pd.Index(ch.load_pwe_seqn(year, base_path).values.reshape(-1))

    # PAXLDAY is stored as a string, so compare it as one
    header = nhn.load_PAXHD(year, base_path)
    valid = header[(header["PAXSTS"] == 1) & (header["PAXLDAY"] == "9")].index

    df_all = nhn.add_demo_labels(adults.loc[adults.index.intersection(valid)])
    df_pwe = nhn.add_demo_labels(adults.loc[adults.index.intersection(pwe_index).intersection(valid)])

    return df_all, df_pwe


def find_frequency_matched_controls(df_all, df_pwe,
                                    control_ratio=DEFAULT_CONTROL_RATIO,
                                    seed=DEFAULT_SEED):
    """
    Frequency match controls to cases across the strata in MATCH_COLS.

    For each combination of matching variables present among the cases, sample
    up to `control_ratio` times as many controls from participants sharing that
    combination. Strata with no eligible controls are skipped, so the achieved
    ratio can be lower than requested.

    Sampling is seeded, so the same inputs always produce the same cohort.

    Returns
    -------
    controls : DataFrame
        The matched controls.
    cases : DataFrame
        The cases that entered matching, i.e. those with complete data on
        every matching variable.
    """
    df_all = df_all.copy()
    df_pwe = df_pwe.copy()

    df_all["age_bin"] = bin_age(df_all["age"])
    df_pwe["age_bin"] = bin_age(df_pwe["age"])

    # A participant missing any matching variable cannot be matched on it
    cases = df_pwe.dropna(subset=MATCH_COLS)
    pool = df_all.dropna(subset=MATCH_COLS)

    # Cases must not also appear as their own controls
    pool = pool.loc[~pool.index.isin(set(cases.index))].copy()

    strata = (
        cases
        .groupby(MATCH_COLS, observed=False)
        .size()
        .reset_index(name="n_pwe")
    )

    rng = np.random.default_rng(seed)

    matched = []
    for _, row in strata.iterrows():
        in_stratum = np.logical_and.reduce([
            pool[col] == row[col] for col in MATCH_COLS
        ])
        eligible = pool.loc[in_stratum]

        if len(eligible) == 0:
            continue

        n_wanted = row["n_pwe"] * control_ratio
        sampled = eligible.sample(
            n=min(len(eligible), n_wanted),
            replace=False,
            random_state=rng.integers(0, 1e9),
        )
        matched.append(sampled)

    controls = pd.concat(matched) if matched else pool.iloc[0:0]

    return controls, cases


def summarise_match(cases, controls, match_cols=None):
    """
    Compare the distribution of each matching variable between the groups.

    Returns a dict of {variable: DataFrame}, so a caller can print it, render
    it, or assert on it.
    """
    match_cols = match_cols or MATCH_COLS

    summary = {}
    for col in match_cols:
        summary[col] = pd.concat(
            {
                "PWE": cases[col].value_counts(normalize=True).round(3),
                "Matched controls": controls[col].value_counts(normalize=True).round(3),
            },
            axis=1,
        ).fillna(0)

    return summary


def missing_lux_files(seqns, year, base_path=None, downsample="5min"):
    """
    Which of these participants have no LUX recording on disk.

    Only relevant to the PAXLUX analysis; PAXMIN needs no such check, as it
    arrives as a single table.
    """
    return [
        int(seqn) for seqn in seqns
        if not paths.lux_file(seqn, year, downsample, base_path).exists()
    ]


def save_matching_results(controls, cases, year, base_path=None, match_type="freq"):
    """
    Write the matched SEQN lists, and return the paths written.

    Writes to the canonical processed directory, which is where the analysis
    reads them from.
    """
    save_dir = paths.processed_dir(year, base_path, create=True)

    control_path = save_dir / f"{match_type}_match_control_{year}.csv"
    case_path = save_dir / f"{match_type}_match_pwe_{year}.csv"

    pd.Series(controls.index.values).to_csv(control_path)
    pd.Series(cases.index.values).to_csv(case_path)

    return control_path, case_path
